application: kaput-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$

builtins:
 - remote_api: on

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: /_ah/queue/async.*
  script: furious_router.app
  login: admin

- url: .*
  script: main.app

